cache:
  key: ${CI_PROJECT_NAME}
  paths:
    - public
    - build
build:
  image: ${CI_REGISTRY}/molpro/profiler
  #  only:
  #    - merge_requests
  script:
    - TOP=$PWD
    - PROJECT_NAME=Profiler
    - git checkout $CI_COMMIT_SHA # because of cache
    - git fetch --tags
    - git reset --hard
    - git clean -f program lib test
    - procs=$(lscpu -p | egrep -v '^#' | wc -l ) || procs=$(sysctl -n hw.physicalcpu) || procs=1; echo $procs processors available
    - cd $TOP; BUILD=build ; mkdir -p $BUILD && cd $BUILD && pwd && cmake $TOP -DFORTRAN=ON -DMPI=ON;  cmake --build . ;  ctest -V -j $procs
    - mkdir -p $TOP/$BUILD/docs/$PROJECT_NAME/html/DoxygenTagFiles && cp $TOP/$BUILD/docs/$PROJECT_NAME/$PROJECT_NAME.tag $TOP/$BUILD/docs/$PROJECT_NAME/html/DoxygenTagFiles
    - mkdir -p $TOP/public
    - . $TOP/$BUILD/project_version.sh ; rsync -a --delete $TOP/$BUILD/docs/${PROJECT_NAME}/html/ $TOP/public/${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    - rm -f  $TOP/public/${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}/${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR}
    - if [ $(git describe --tags --abbrev=0 --always HEAD) = $(git describe --tags --abbrev=0 --always origin/master) ]; then cd $TOP/public; rm -f latest; ln -s ${PROJECT_VERSION_MAJOR}.${PROJECT_VERSION_MINOR} latest ; rm -f ./index.html; fi
    - echo '<head><meta http-equiv="refresh" content="0; URL=latest"></head>' > $TOP/public/index.html
pages:
  stage: deploy
  only:
    - tags
  script:
    - echo nothing
  artifacts:
    paths:
      - public

